# Generated by Django 4.1.7 on 2023-04-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0003_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
