# Generated by Django 4.1.7 on 2023-04-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
