# Generated by Django 4.1.7 on 2023-04-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0007_remove_customuser_cpassword_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
