# Generated by Django 4.1.7 on 2023-04-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0015_alter_customuser_cid_alter_medical_store_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=10098),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='role',
            field=models.CharField(choices=[('MS', 'MS'), ('HS', 'HS'), ('LS', 'LS')], max_length=2),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=65090),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=22302),
        ),
    ]
