# Generated by Django 4.1.7 on 2023-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0019_checkout_alter_customuser_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=10052),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=91326),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=52745),
        ),
    ]
