# Generated by Django 4.1.7 on 2023-04-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0023_alter_checkout_price_alter_checkout_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=80198),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=99734),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=19280),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(),
        ),
    ]
