# Generated by Django 4.1.7 on 2023-04-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0024_alter_checkout_discount_alter_customuser_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=77594),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='cpassword',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=21776),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=84911),
        ),
    ]
