# Generated by Django 4.1.7 on 2023-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0029_alter_customuser_cid_alter_list_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=41658),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=530072),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=63481),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=61507),
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.IntegerField(default=1519052),
        ),
    ]
