# Generated by Django 4.1.7 on 2023-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0030_alter_customuser_cid_alter_list_mid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=30159),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=716857),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=69932),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=23324),
        ),
    ]
