# Generated by Django 4.1.7 on 2023-04-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0036_delete_order_alter_customuser_cid_alter_list_mid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aid', models.IntegerField(default=50274184, unique=True)),
                ('cid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('patient', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('total', models.IntegerField()),
                ('Medicine_total', models.IntegerField()),
                ('Final_total', models.IntegerField()),
                ('Appointment_date', models.DateField()),
                ('Appointment_time', models.TimeField()),
                ('report', models.FileField(upload_to='report/')),
                ('status', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField(default=24597037, unique=True)),
                ('cid', models.IntegerField()),
                ('sid', models.IntegerField()),
                ('mid', models.IntegerField()),
                ('medicine', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('Medicine_total', models.IntegerField()),
                ('Final_total', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=25519, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=570620, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=57221, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=73897, unique=True),
        ),
    ]
