# Generated by Django 4.1.7 on 2023-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0038_alter_appointment_aid_alter_customuser_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Aid',
            field=models.IntegerField(default=17622207, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=70067, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=193453, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=69330, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=55846, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(max_length=50),
        ),
    ]
