# Generated by Django 4.1.7 on 2023-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0039_alter_appointment_aid_alter_customuser_cid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=76841, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=355342, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=38602, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=46350, unique=True),
        ),
    ]
