# Generated by Django 4.1.7 on 2023-04-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0041_appointment_alter_customuser_cid_alter_list_mid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Final_total',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Medicine_total',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Aid',
            field=models.IntegerField(default=57924112, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=60154, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=569712, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=45337, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=30494, unique=True),
        ),
    ]
