# Generated by Django 4.1.7 on 2023-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0042_remove_appointment_final_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=97613, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=243370, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=85623, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=83154, unique=True),
        ),
    ]
