# Generated by Django 4.1.7 on 2023-04-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0044_appointment_alter_customuser_cid_alter_list_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Aid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=67727, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=868305, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=72536, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=52853, unique=True),
        ),
    ]
