# Generated by Django 4.1.7 on 2023-04-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0046_delete_appointment_alter_customuser_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=10890, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=309572, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=44599, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=35055, unique=True),
        ),
    ]
