# Generated by Django 4.1.7 on 2023-04-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0050_customuser_alter_list_mid_alter_medical_store_sid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=645226, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=68868, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=95620, unique=True),
        ),
    ]
