# Generated by Django 4.1.7 on 2023-04-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0052_customuser_alter_list_mid_alter_medical_store_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cid',
            field=models.IntegerField(default=78831, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=514595, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=32694, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=61397, unique=True),
        ),
    ]
