# Generated by Django 4.1.7 on 2023-04-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0054_alter_customuser_cid_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='mid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lab',
            name='cid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=507473, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=52990, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=28082, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cid',
            field=models.CharField(max_length=10),
        ),
    ]
