# Generated by Django 4.1.7 on 2023-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0058_alter_list_mid_alter_medical_store_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='mid',
            field=models.IntegerField(default=95776443, unique=True),
        ),
        migrations.AlterField(
            model_name='medical_store',
            name='sid',
            field=models.IntegerField(default=642885, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mid',
            field=models.IntegerField(default=6549542, unique=True),
        ),
    ]
