# Generated by Django 4.1.7 on 2023-05-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi', '0060_company_delete_appointment_delete_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(default=266753, unique=True),
        ),
    ]
